Remove dot in the version

diff --git a/bin/fink_ssoft b/bin/fink_ssoft
--- a/bin/fink_ssoft
+++ b/bin/fink_ssoft
@@ -13,7 +13,11 @@
 # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 # See the License for the specific language governing permissions and
 # limitations under the License.
+set -e
 source ~/.bash_profile
+
+# re-download latest information
+export ROCKS_CACHE_DIR="no-cache"
 
 SINFO="\xF0\x9F\x9B\x88"
 SERROR="\xE2\x9D\x8C"
@@ -235,9 +239,9 @@ if [[ ${UPDATE_DATA} == true ]]; then
   CURRENT_YYYYMM=`date +"%Y%m"`
   YEAR=${CURRENT_YYYYMM:0:4}
   MONTH=${CURRENT_YYYYMM:4:2}
-  $(hdfs dfs -test -d sso_ztf_lc_aggregated_${YEAR}.${MONTH}.parquet)
+  $(hdfs dfs -test -d sso_ztf_lc_aggregated_${YEAR}${MONTH}.parquet)
   if [[ $? == 0 ]]; then
-    echo -e >&2 "${SERROR} File sso_ztf_lc_aggregated_${YEAR}.${MONTH}.parquet exist. Move it before aggregation."
+    echo -e >&2 "${SERROR} File sso_ztf_lc_aggregated_${YEAR}${MONTH}.parquet exist. Move it before aggregation."
     echo -e >&2 "${SSTOP} Merging aborted..."
     exit 1
   else
