v4 feedback from prod (#955)
* Remove unused args for distribution

* Make the topic optional

* Interpret correctly the date operand

* Remov unused files

* Update auth

* Update CLI parsing

* Fix CLI parsing for fink_db

* Update documentation for launcher

* Update doc for fink

* Update README

* Update documentation for wrappers

* Update logic for fink_db

* Update exception

* Missing fi

* Update docu

* Documentation

* Fix typo

* Fix wrong import

diff --git a/bin/fink b/bin/fink
--- a/bin/fink
+++ b/bin/fink
@@ -15,6 +15,12 @@
 # limitations under the License.
 set -e
 
+SINFO="\xF0\x9F\x9B\x88"
+SERROR="\xE2\x9D\x8C"
+SSTOP="\xF0\x9F\x9B\x91"
+SSTEP="\xF0\x9F\x96\xA7"
+SDONE="\xE2\x9C\x85"
+
 # Show help if no arguments is given
 if [[ $1 == "" ]]; then
   HELP_ON_SERVICE="-h"
@@ -26,8 +32,8 @@ while [ "$#" -gt 0 ]; do
   case "$1" in
     "start"|"stop")
       MODE="$1"
-      if [[ $2 == "" || $2 == "-c" ]]; then
-        echo "$1 requires an argument. ${message_service}" >&2
+      if [[ $2 == "" ]]; then
+        echo -e "${SERROR} $1 requires an argument." >&2
         exit 1
       fi
       service="$2"
@@ -35,11 +41,11 @@ while [ "$#" -gt 0 ]; do
       ;;
     "show")
       nservice=$(ps ax | grep -i 'fink start' | grep -v grep | wc -l)
-      echo -e "$nservice Fink service(s) running: "
+      echo -e "${SINFO} $nservice Fink service(s) running: "
       ps aux | head -1
       ps aux | grep -i 'fink start' | grep -v grep
       ps aux | grep -i 'gcn_stream start' | grep -v grep
-      echo "Use <fink stop service_name> to stop a service."
+      echo -e "${SINFO} Use <fink stop service_name> -s <survey> to stop a service."
       exit
       ;;
     -h)
@@ -51,10 +57,6 @@ while [ "$#" -gt 0 ]; do
       shift 2
       ;;
     -c)
-      if [[ $2 == "" || $2 == "-s" ]]; then
-        echo "$1 requires an argument. ${message_conf}" >&2
-        exit 1
-      fi
       conf="$2"
       shift 2
       ;;
@@ -100,7 +102,7 @@ while [ "$#" -gt 0 ]; do
       ;;
     --version)
       python3 -c "import fink_broker; print(fink_broker.__version__)"
-      exit
+      exit 0
       ;;
     --noscience)
       NOSCIENCE="--noscience"
@@ -117,57 +119,90 @@ while [ "$#" -gt 0 ]; do
   esac
 done
 
-services=`/usr/bin/ls ${FINK_HOME}/bin/${SURVEY}`
-message_service="Available services are: ${services}"
-message_conf="Typical configuration would be $PWD/conf/fink.conf.dev"
-message_help="""
-Handle Kafka streams received by Apache Spark\n\n
-Usage:\n
-    \tto start a service: fink start <service> [-h] [-s <survey>] [-c <conf>] [--simulator]\n
-    \tto stop a service : fink stop  <service> [-h] [-c <conf>]\n
-    \tto show services  : fink show \n\n
+__usage="
+fink controls the Fink broker real-time and database operations.
 
-To get this help: \n
-\tfink -h \n\n
+  Find more information on Fink at https://fink-broker.org
 
-To get help for a service: \n
-\tfink start <service> -h\n\n
+Usage: $(basename $0) [OPTIONS]
 
-$message_service\n\n
+Options:
+  -s          Survey name (ztf, rubin). Default is ztf.
+  start       Start a service. The list of available services is given at ${FINK_HOME}/bin/${SURVEY}
+  stop        Stop a running service.
+  show        Show running services.
+  -h          Show this help.
+  --version   If specified, show the version of the code.
 
-$message_conf\n\n
+Service options:
+  -h                    Show help for the service.
+  -c                    Path to configuration file.
+  -conf_distribution    Path to the extra configuration file for the distribute service.
+  -night                Night to process with format YYYYMMDD
+  -topic                Kafka topic name to poll data from.
+  -index_table          Name of the index table to populate.
+  -driver_memory        Memory to use for the driver (see Spark options)
+  -executor_memory      Memory to use for each executor (see Spark options)
+  -spark-cores-max      Total number of cores to use for all executors (see Spark options)
+  -spark-executor-cores Number of cores per executor (see Spark options)
+  -exit_after           Number of seconds after which the service should stop.
+  --simulator           If specified, run in simulation mode.
+  --noscience           If specified, do not enrich data with science modules.
 
-To see the running processes: \n
-\tfink show \n\n
+Examples:
+  Start polling for an hour:
+  fink start stream2raw -s ztf -night 20190101 \t
+	-topic ztf_20190101 -driver_memory 4g -executor_memory 2g \t
+	-spark-cores-max 4 -spark-executor-cores 1 -exit_after 3600
 
-To stop a service or all running processes: \n
-\tfink stop <service or all> \n
-"""
+  Archive data in HBase:
+  fink start archive_science -s ztf -night 20190101 \t
+  	-driver-memory 4g -executor-memory 4g \t
+	-spark-cores-max 9 -spark-executor-cores 1
+
+Notes: useful wrappers can be found at ${FINK_HOME}/scheduler/${SURVEY}
+
+Scheduler: Typical scheduler at VirtualData is
+# Fink real-time
+01 00 * * * /home/julien.peloton/fink-broker/scheduler/ztf/launch_stream.sh
+
+# Database service
+05 20 * * * /home/julien.peloton/fink-broker/scheduler/ztf/launch_db.sh
+
+# SSOFT - once a month
+0 0 1 * * /home/julien.peloton/fink-broker/scheduler/ztf/launch_ssoft.sh
+0 12 1 * * /home/julien.peloton/fink-broker/scheduler/ztf/launch_sso_resolver.sh
+
+# Operation reports four times a day
+0 07 * * * /home/julien.peloton/fink-broker/scheduler/ztf/check_status.sh --telegram
+0 12 * * * /home/julien.peloton/fink-broker/scheduler/ztf/check_status.sh --telegram
+0 17 * * * /home/julien.peloton/fink-broker/scheduler/ztf/check_status.sh --telegram
+0 22 * * * /home/julien.peloton/fink-broker/scheduler/ztf/check_status.sh --telegram
+"
 
 if [[ $SURVEY == "" ]]; then
-  echo -e "You need to specify a survey, e.g. fink -s ztf [options]"
+  echo -e "${SERROR} You need to specify a survey, e.g. fink -s ztf [options]"
   exit 1
 fi
 
 if [[ $service == "" ]] && [[ ${HELP_ON_SERVICE} == "-h" ]]; then
-  echo -e $message_help
+  echo -e "$__usage"
   exit 1
 fi
 
 # Check service exists
-if [[ ! -f ${FINK_HOME}/bin/${SURVEY}/${service}.py ]]; then
+if [[ ! -f ${FINK_HOME}/bin/${SURVEY}/${service}.py ]] && [[ ${service} != "all" ]]; then
   # In case you give an unknown service
-  echo "unknown service: $service" >&2
-  echo $message_service
+  echo -e "${SERROR} unknown service: $service" >&2
   exit 1
 fi
 
 # Check if the conf file exists
 if [[ -f $conf ]]; then
-  echo "Reading custom Fink configuration file from " $conf
+  echo -e "${SINFO} Reading custom Fink configuration file from " $conf
   source $conf
 else
-  echo "Reading default Fink conf from " ${FINK_HOME}/conf/${SURVEY}/fink.conf.prod
+  echo -e "${SINFO} Reading default Fink conf from " ${FINK_HOME}/conf/${SURVEY}/fink.conf.prod
   source ${FINK_HOME}/conf/${SURVEY}/fink.conf.prod
 fi
 
@@ -177,14 +212,18 @@ fi
 
 # Stop a service
 if [[ $MODE == "stop" ]]; then
+  echo -e "${SSTEP} Stopping services..."
   if [[ $service == "all" ]]; then
+    pkill -f launch_db.sh
+    pkill -f launch_stream.sh
     pkill -f stream2raw
     pkill -f raw2science
     pkill -f distribute
   else
     pkill -f $service
   fi
-  exit 1
+  echo -e "${SDONE} $service stopped"
+  exit 0
 fi
 
 # Grab Fink and Python version numbers
@@ -197,8 +236,15 @@ if [[ $DEPLOY_FINK_PYTHON == "true" ]]; then
   cd $FINK_HOME
   python3 setup.py bdist_egg
   PYTHON_EXTRA_FILE="--py-files ${FINK_HOME}/dist/fink_broker-${FINK_VERSION}-py${PYTHON_VERSION}.egg"
-  echo "Distributing ${PYTHON_EXTRA_FILE}"
+  echo -e "${SINFO} Distributing ${PYTHON_EXTRA_FILE}"
   cd -
+fi
+
+# Topic required only for stream2raw
+if [[ ${KAFKA_TOPIC} ]]; then
+  KAFKA_TOPIC="-topic ${KAFKA_TOPIC}"
+else
+  KAFKA_TOPIC=""
 fi
 
 # Only if the operator pass an index table
@@ -218,10 +264,10 @@ fi
 DISTRIBUTE_OPTIONS=""
 if [[ $service == "distribute" ]]; then
   if [[ -f $conf_distribution ]]; then
-    echo "Reading custom Fink distribution configuration file from " $conf_distribution
+    echo -e "${SINFO} Reading custom Fink distribution configuration file from " $conf_distribution
     source $conf_distribution
   else
-    echo "Reading default Fink distribution conf from " ${FINK_HOME}/conf/${SURVEY}/fink.conf.distribution
+    echo -e "${SINFO} Reading default Fink distribution conf from " ${FINK_HOME}/conf/${SURVEY}/fink.conf.distribution
     source ${FINK_HOME}/conf/${SURVEY}/fink.conf.distribution
   fi
 
@@ -238,7 +284,6 @@ spark-submit --master ${SPARK_MASTER} \
   ${FINK_HOME}/bin/${SURVEY}/${service}.py ${HELP_ON_SERVICE} \
   -producer ${SURVEY} \
   -servers ${KAFKA_IPPORT} \
-  -topic ${KAFKA_TOPIC} \
   -night ${NIGHT} \
   -schema ${FINK_ALERT_SCHEMA} \
   -startingoffsets_stream ${KAFKA_STARTING_OFFSET} \
@@ -252,6 +297,7 @@ spark-submit --master ${SPARK_MASTER} \
   -science_db_name ${SCIENCE_DB_NAME} \
   -science_db_catalogs ${SCIENCE_DB_CATALOGS} \
   -tns_folder ${TNS_FOLDER} \
-  ${DISTRIBUTE_OPTIONS} ${TNS_RAW_OUTPUT} ${INDEXTABLE} ${NOSCIENCE} \
+  ${KAFKA_TOPIC} ${DISTRIBUTE_OPTIONS} ${TNS_RAW_OUTPUT} ${INDEXTABLE} ${NOSCIENCE} \
   -log_level ${LOG_LEVEL} ${EXIT_AFTER}
 
+echo -e "${SDONE} $service exiting"
diff --git a/bin/fink_db b/bin/fink_db
--- a/bin/fink_db
+++ b/bin/fink_db
@@ -15,6 +15,12 @@
 # limitations under the License.
 source ~/.bash_profile
 
+SINFO="\xF0\x9F\x9B\x88"
+SERROR="\xE2\x9D\x8C"
+SSTOP="\xF0\x9F\x9B\x91"
+SSTEP="\xF0\x9F\x96\xA7"
+SDONE="\xE2\x9C\x85"
+
 # TODO: add help
 # Show help if no arguments is given
 if [[ $1 == "" ]]; then
@@ -37,26 +43,6 @@ while [ "$#" -gt 0 ]; do
       conf="$2"
       shift 2
       ;;
-    --merge)
-      MERGE=true
-      shift 2
-      ;;
-    --main_table)
-      MAIN_TABLE=true
-      shift 2
-      ;;
-    --index_tables)
-      INDEX_TABLES=true
-      shift 2
-      ;;
-    --clean_night)
-      CLEAN_NIGHT=true
-      shift 2
-      ;;
-    --clean_merge)
-      CLEAN_MERGE=true
-      shift 2
-      ;;
     -night)
       NIGHT="$2"
       shift 2
@@ -77,6 +63,26 @@ while [ "$#" -gt 0 ]; do
       SPARK_EXECUTOR_CORES="$2"
       shift 2
       ;;
+    --merge)
+      MERGE=true
+      shift 1
+      ;;
+    --main_table)
+      MAIN_TABLE=true
+      shift 1
+      ;;
+    --index_tables)
+      INDEX_TABLES=true
+      shift 1
+      ;;
+    --clean_night)
+      CLEAN_NIGHT=true
+      shift 1
+      ;;
+    --delete_merge)
+      DELETE_MERGE=true
+      shift 1
+      ;;
     -*)
       echo "unknown option: $1" >&2
       exit 1
@@ -88,35 +94,80 @@ while [ "$#" -gt 0 ]; do
   esac
 done
 
+__usage="
+fink_db is a wrapper around fink to control the database operations.
+
+Usage: $(basename $0) [OPTIONS]
+
+Options:
+  -h                    Show this help.
+  -s                    Survey name (ztf, rubin). Default is ztf.
+  -c                    Path to configuration file.
+  -night                Night to process with format YYYYMMDD
+  -driver_memory        Memory to use for the driver (see Spark options)
+  -executor_memory      Memory to use for each executor (see Spark options)
+  -spark-cores-max      Total number of cores to use for all executors (see Spark options)
+  -spark-executor-cores Number of cores per executor (see Spark options)
+  --merge               Merge small files from streaming operations from ONLINE_DATA_PREFIX into AGG_DATA_PREFIX (see configuration file)
+  --main_table          Push night data to HBase main table
+  --index_tables        Push night data to HBase index tables
+  --clean_night         Clean temporary files from the night. Should be run once data is merged.
+  --delete_merge        Delete merged files in case of error (then restart using --merge).
+
+Notes: another useful wrapper can be found at ${FINK_HOME}/scheduler/${SURVEY}/launch_db.sh
+
+Examples:
+fink_db -s ztf --merge                # merge files
+fink_db -s ztf --main_table           # Push data to HBase
+fink_db -s ztf --index_tables         # Push data to HBase index tables
+fink_db -s ztf --clean_night          # Clean temp files for the next night
+"
+
+if [[ $service == "" ]] && [[ ${HELP_ON_SERVICE} == "-h" ]]; then
+  echo -e "$__usage"
+  exit 0
+fi
+
+hdfs version >/dev/null 2>&1 || { echo -e >&2 "${SERROR} hdfs is not found. Aborting."; exit 1; }
+
+if [[ $SURVEY == "" ]]; then
+  echo -e "${SERROR} You need to specify a survey, e.g. fink -s ztf [options]"
+  exit 1
+fi
+
 if [[ ! $NIGHT ]]; then
   # Current night
   NIGHT=`date +"%Y%m%d"`
 fi
-echo "Processing night ${NIGHT} for survey ${SURVEY}"
+echo -e "${SINFO} Processing night ${NIGHT} for survey ${SURVEY}"
 
 # Check if the conf file exists
 if [[ -f $conf ]]; then
-  echo "Reading custom Fink configuration file from " $conf
+  echo -e "${SINFO} Reading custom Fink configuration file from " $conf
 else
-  echo "Reading default Fink conf from " ${FINK_HOME}/conf/${SURVEY}/fink.conf.prod
+  echo -e "${SINFO} Reading default Fink conf from " ${FINK_HOME}/conf/${SURVEY}/fink.conf.prod
   conf=${FINK_HOME}/conf/${SURVEY}/fink.conf.prod
 fi
 
+source $conf
+
 # Merge streaming data
 if [[ ${MERGE} == true ]]; then
-  $(hdfs dfs -test -d /user/julien.peloton/online/science/${NIGHT})
+  $(hdfs dfs -test -d ${ONLINE_DATA_PREFIX}/science/${NIGHT})
   if [[ $? == 0 ]]; then
-    echo "merge_and_clean"
+    echo -e "${SSTEP} Merge"
     # if nothing specified, get default
     if [[ ! ${DRIVER_MEMORY} ]]; then
       RESOURCES="-driver-memory 4g -executor-memory 16g -spark-cores-max 80 -spark-executor-cores 8"
     else
       RESOURCES="-driver-memory ${DRIVER_MEMORY} -executor-memory ${EXECUTOR_MEMORY} -spark-cores-max ${SPARK_CORE_MAX} -spark-executor-cores ${SPARK_EXECUTOR_CORES}"
     fi
+    echo -e "${SINFO} Using Spark resources: ${RESOURCES}"
     fink start merge -s ${SURVEY} -c ${conf} -night ${NIGHT} ${RESOURCES} > ${FINK_HOME}/broker_logs/merge_${SURVEY}_${NIGHT}.log 2>&1
   else
-    echo "No data at /user/julien.peloton/online/science/${NIGHT}"
-    echo "Merging aborted..."
+    echo -e "${SERROR} No data at ${ONLINE_DATA_PREFIX}/science/${NIGHT}"
+    echo -e "${SSTOP} Merging aborted..."
+    exit 1
   fi
 fi
 
@@ -130,21 +181,33 @@ MONTH=${NIGHT:4:2}
 DAY=${NIGHT:6:2}
 
 # Aggregated data is available
-$(hdfs dfs -test -d /user/julien.peloton/archive/science/year=${YEAR}/month=${MONTH}/day=${DAY})
-if [[ $? == 0 ]]; then
-  if [[ ${MAIN_TABLE} == true ]]; then
-    echo "science_archival"
-    fink start archive_science -s ${SURVEY} -c ${conf} -night ${NIGHT} ${RESOURCES} > ${FINK_HOME}/broker_logs/archive_science_${SURVEY}_${NIGHT}.log 2>&1
-  fi
+$(hdfs dfs -test -d ${AGG_DATA_PREFIX}/science/year=${YEAR}/month=${MONTH}/day=${DAY})
+HAS_DATA=$?
 
-  if [[ ${INDEX_TABLES} == true ]]; then
-    echo "Download latest TNS data"
+if [[ ${MAIN_TABLE} == true ]]; then
+  if [[ ${HAS_DATA} == 0 ]]; then
+    echo -e "${SINFO} Using Spark resources: ${RESOURCES}"
+    echo -e "${SSTEP} Science archival"
+    fink start archive_science -s ${SURVEY} -c ${conf} -night ${NIGHT} ${RESOURCES} > ${FINK_HOME}/broker_logs/archive_science_${SURVEY}_${NIGHT}.log 2>&1
+  else
+    echo -e "${SERROR} No data at ${AGG_DATA_PREFIX}/science/year=${YEAR}/month=${MONTH}/day=${DAY}"
+    echo -e "${SERROR} Did you run --merge before?"
+    echo -e "${SSTOP} Pushing data to tables aborted..."
+    exit 1
+  fi
+fi
+
+if [[ ${INDEX_TABLES} == true ]]; then
+  if [[ ${HAS_DATA} == 0 ]]; then
+    echo -e "${SINFO} Using Spark resources: ${RESOURCES}"
+
+    echo -e "${SSTEP} 1/12: Download latest TNS data"
     fink start tns_resolver -s ${SURVEY} -c ${conf} -night ${NIGHT} ${RESOURCES} > ${FINK_HOME}/broker_logs/tns_resolver_${SURVEY}_${NIGHT}.log 2>&1
 
-    echo "images_archival"
+    echo -e "${SSTEP} 2/12: images_archival"
     fink start archive_images -s ${SURVEY} -c ${conf} -night ${NIGHT} ${RESOURCES} > ${FINK_HOME}/broker_logs/archive_images_${SURVEY}_${NIGHT}.log 2>&1
 
-    echo "Update index tables"
+    echo -e "${SSTEP} 3/12: Update index tables"
     fink start index_archival -s ${SURVEY} -c ${conf} -night ${NIGHT} ${RESOURCES} --index_table pixel128_jdstarthist_objectId > ${FINK_HOME}/broker_logs/index_pixel128_jd_objectId_${SURVEY}_${NIGHT}.log 2>&1
     fink start index_archival -s ${SURVEY} -c ${conf} -night ${NIGHT} ${RESOURCES} --index_table class_jd_objectId > ${FINK_HOME}/broker_logs/index_class_jd_objectId_${SURVEY}_${NIGHT}.log 2>&1
     fink start index_archival -s ${SURVEY} -c ${conf} -night ${NIGHT} ${RESOURCES} --index_table upper_objectId_jd > ${FINK_HOME}/broker_logs/index_upper_objectId_jd_${SURVEY}_${NIGHT}.log 2>&1
@@ -153,60 +216,66 @@ if [[ $? == 0 ]]; then
     fink start index_archival -s ${SURVEY} -c ${conf} -night ${NIGHT} ${RESOURCES} --index_table tracklet_objectId > ${FINK_HOME}/broker_logs/index_tracklet_objectId_${SURVEY}_${NIGHT}.log 2>&1
     fink start index_archival -s ${SURVEY} -c ${conf} -night ${NIGHT} ${RESOURCES} --index_table tns_jd_objectId > ${FINK_HOME}/broker_logs/index_tns_jd_objectId_${SURVEY}_${NIGHT}.log 2>&1
 
-    echo "Push TNS candidates"
+    echo -e "${SSTEP} 4/12: Push TNS candidates"
     fink start push_to_tns -s ${SURVEY} -c ${conf} -night ${NIGHT} ${RESOURCES} > ${FINK_HOME}/broker_logs/push_to_tns_${SURVEY}_${NIGHT}.log 2>&1
 
-    echo "Push Anomaly candidates"
+    echo -e "${SSTEP} 5/12: Push Anomaly candidates"
     fink start archive_anomaly -s ${SURVEY} -c ${conf} -night ${NIGHT} ${RESOURCES} > ${FINK_HOME}/broker_logs/archive_anomaly_${SURVEY}_${NIGHT}.log 2>&1
 
-    echo "Push Active Learning loop candidates"
+    echo -e "${SSTEP} 6/12: Push Active Learning loop candidates"
     fink start archive_ia_active_learning -s ${SURVEY} -c ${conf} -night ${NIGHT} ${RESOURCES} > ${FINK_HOME}/broker_logs/archive_ia_active_learning_${SURVEY}_${NIGHT}.log 2>&1
 
-    echo "Push Hostless candidates"
+    echo -e "${SSTEP} 7/12: Push Hostless candidates"
     fink start archive_hostless -s ${SURVEY} -c ${conf} -night ${NIGHT} ${RESOURCES} > ${FINK_HOME}/broker_logs/archive_hostless_${SURVEY}_${NIGHT}.log 2>&1
 
-    echo "Send Dwarf AGN candidates"
+    echo -e "${SSTEP} 8/12: Send Dwarf AGN candidates"
     fink start archive_dwarf_agn -s ${SURVEY} -c ${conf} -night ${NIGHT} ${RESOURCES} > ${FINK_HOME}/broker_logs/archive_dwarf_agn_${SURVEY}_${NIGHT}.log 2>&1
 
-    echo "Send Known TDE candidates"
+    echo -e "${SSTEP} 9/12: Send Known TDE candidates"
     fink start archive_known_tde -s ${SURVEY} -c ${conf} -night ${NIGHT} ${RESOURCES} > ${FINK_HOME}/broker_logs/archive_known_tde_${SURVEY}_${NIGHT}.log 2>&1
 
-    echo "Update statistics"
+    echo -e " ${SSTEP}10/12: Update statistics"
     fink start archive_statistics -s ${SURVEY} -c ${conf} -night ${NIGHT} ${RESOURCES} > ${FINK_HOME}/broker_logs/archive_statistics_${SURVEY}_${NIGHT}.log 2>&1
 
-    echo "Call to Fink-Fat"
+    echo -e "${SSTEP} 11/12: Call to Fink-Fat"
     fink_fat associations candidates --config $FINK_HOME/conf/fink_fat.conf --night ${YEAR}-${MONTH}-${DAY} --verbose > ${FINK_HOME}/broker_logs/fink_fat_association_${NIGHT}.log 2>&1
     fink_fat solve_orbit candidates local --config $FINK_HOME/conf/fink_fat.conf --verbose > ${FINK_HOME}/broker_logs/fink_fat_solve_orbit_${NIGHT}.log 2>&1
 
-    echo "Push SSO candidates to HBase"
+    echo -e "${SSTEP} 12/12: Push SSO candidates to HBase"
     fink start archive_sso_cand -s ${SURVEY} -c ${conf} -night ${NIGHT} ${RESOURCES} > ${FINK_HOME}/broker_logs/archive_sso_cand_${SURVEY}_${NIGHT}.log 2>&1
+  else
+    echo -e "${SERROR} No data at ${AGG_DATA_PREFIX}/science/year=${YEAR}/month=${MONTH}/day=${DAY}"
+    echo -e "${SERROR} Did you run --merge before?"
+    echo -e "${SSTOP} Pushing data to tables aborted..."
+    exit 1
   fi
-else
-    echo "No data at /user/julien.peloton/archive/science/year=${YEAR}/month=${MONTH}/day=${DAY}"
-    echo "Did you run --merge before?"
-    echo "Pushing data to tables aborted..."
 fi
 
-if [[ $CLEAN_MERGE == true ]]; then
-  echo "Cleaning merged files..."
-  # If merge went wrong -- clean
-  hdfs dfs -rm -r /user/julien.peloton/archive/raw/year=${YEAR}/month=${MONTH}/day=${DAY}
-  hdfs dfs -rm -r /user/julien.peloton/archive/science/year=${YEAR}/month=${MONTH}/day=${DAY}
+if [[ $DELETE_MERGE == true ]]; then
+  if [[ ${HAS_DATA} == 0 ]]; then
+    echo -e "${SINFO} Deleting merged files on HDFS..."
+    # If merge went wrong -- clean
+    hdfs dfs -rm -r ${AGG_DATA_PREFIX}/raw/year=${YEAR}/month=${MONTH}/day=${DAY}
+    hdfs dfs -rm -r ${AGG_DATA_PREFIX}/science/year=${YEAR}/month=${MONTH}/day=${DAY}
+  else
+    echo -e "${SERROR} No data at ${AGG_DATA_PREFIX}/science/year=${YEAR}/month=${MONTH}/day=${DAY}"
+    echo -e "${SSTOP} Nothing to delete"
+    exit 1
+  fi
 fi
 
 if [[ ${CLEAN_NIGHT} == true ]]; then
   # Delete temporary files after the night
-  $(hdfs dfs -test -d /user/julien.peloton/archive/science/year=${YEAR}/month=${MONTH}/day=${DAY})
-  if [[ $? == 0 ]]; then
-    echo "Cleaning temporary files..."
+  if [[ $HAS_DATA == 0 ]]; then
+    echo -e "${SINFO} Cleaning temporary files on HDFS..."
     # Remove data path
-    hdfs dfs -rm -r /user/julien.peloton/online/raw/${NIGHT}
-    hdfs dfs -rm -r /user/julien.peloton/online/science/${NIGHT}
+    hdfs dfs -rm -r ${ONLINE_DATA_PREFIX}/raw/${NIGHT}
+    hdfs dfs -rm -r ${ONLINE_DATA_PREFIX}/science/${NIGHT}
 
     # Remove checkpoints
-    hdfs dfs -rm -r /user/julien.peloton/online/raw_checkpoint/${NIGHT}
-    hdfs dfs -rm -r /user/julien.peloton/online/science_checkpoint/${NIGHT}
-    hdfs dfs -rm -r /user/julien.peloton/online/kafka_checkpoint/${NIGHT}
+    hdfs dfs -rm -r ${ONLINE_DATA_PREFIX}/raw_checkpoint/${NIGHT}
+    hdfs dfs -rm -r ${ONLINE_DATA_PREFIX}/science_checkpoint/${NIGHT}
+    hdfs dfs -rm -r ${ONLINE_DATA_PREFIX}/kafka_checkpoint/${NIGHT}
 
     # Remove checkpoints for fink-mm
     hdfs dfs -rm -r /user/julien.peloton/fink_mm/gcn_x_ztf/online/_spark_metadata
@@ -214,7 +283,10 @@ if [[ ${CLEAN_NIGHT} == true ]]; then
     hdfs dfs -rm -r /user/julien.peloton/fink_mm/gcn_x_ztf/mm_distribute_checkpoint
 
   else
-    echo "No data at /user/julien.peloton/archive/science/year=${YEAR}/month=${MONTH}/day=${DAY}"
-    echo "Cleaning aborted..."
+    echo -e "${SERROR} No data at ${AGG_DATA_PREFIX}/science/year=${YEAR}/month=${MONTH}/day=${DAY}"
+    echo -e "${SSTOP} Cleaning aborted..."
+    exit 1
   fi
 fi
+
+echo -e "${SDONE} done!"
