Add a new service in the SSOFT controller to construct bulk data

diff --git a/bin/fink_ssoft b/bin/fink_ssoft
--- a/bin/fink_ssoft
+++ b/bin/fink_ssoft
@@ -113,6 +113,10 @@ while [ "$#" -gt 0 ]; do
       TRANSFER_SSOFT=true
       shift 1
       ;;
+    --construct-bulk)
+      CONSTRUCT_BULK=true
+      shift 1
+      ;;
     -*)
       echo "unknown option: $1" >&2
       exit 1
@@ -150,15 +154,17 @@ Options:
   --link-ssoft          Create a version agnostic SSOFT folder, with the latest version data
   --list-ssoft          List all available SSOFT on HDFS
   --transfer-ssoft      Transfer SSOFT to HDFS, and backup it. Read from -ssoft_outfolder 
+  --construct-bulk      Join the aggregated data and SSOFT to build bulk file
 
 Examples:
 fink_ssoft -s ztf --reconstruct-data                          # Reconstruct all database
 fink_ssoft -s ztf --update-data                               # Add last month data
 fink_ssoft -s ztf --list-data                                 # List all aggregated files
 fink_ssoft -s ztf --run-ssoft -model SHG1G2                   # Compute SHG1G2 SSOFT
-fink_ssoft -s ztf --run-ssoft -model SHG1G2 -version 202504  # Compute SHG1G2 SSOFT until 2025/04
+fink_ssoft -s ztf --run-ssoft -model SHG1G2 -version 202504   # Compute SHG1G2 SSOFT until 2025/04
 fink_ssoft -s ztf --run-ssoft -model SHG1G2 -limit 10         # Compute SHG1G2 SSOFT with 100 objects only
 fink_ssoft -s ztf --run-ssoft -model SHG1G2 -min 100          # Compute SHG1G2 SSOFT for objects with at least 100 observations
+fink_ssoft -s ztf --construct-bulk                            # Join the aggregated data and SSOFT to build bulk file
 
 Notes: Typically the schedule is to invoke once a month the commands:
 fink_ssoft -s ztf --update-data
@@ -168,6 +174,7 @@ fink_ssoft -s ztf --run-ssoft -model HG1G2
 fink_ssoft -s ztf --run-ssoft -model SHG1G2
 fink_ssoft -s ztf --run-ssoft -model SSHG1G2
 fink_ssoft -s ztf --transfer_ssoft
+fink_ssoft -s ztf --construct-bulk
 
 Notes: If you lose all your ephemerides data, just reconstruct everything with
 fink_ssoft -s ztf --reconstruct-data
@@ -375,3 +382,23 @@ if [[ ${TRANSFER_SSOFT} == true ]]; then
 
 fi
 
+if [[ ${CONSTRUCT_BULK} == true ]]; then
+  # check last aggregation exist
+  is_data=$(hdfs dfs -test -d sso_ztf_lc_aggregated_${YEAR}${MONTH}.parquet)
+  if [[ $? == 0 ]]; then
+    echo -e "Computing the SSO BULK..."
+    # Run the script
+    spark-submit \
+      --master ${SPARK_MASTER} \
+      --packages ${FINK_PACKAGES} --jars ${FINK_JARS} \
+      ${EXTRA_SPARK_CONFIG} ${RESOURCES} \
+      --conf spark.sql.execution.arrow.pyspark.enabled=true\
+      --conf spark.kryoserializer.buffer.max=512m\
+      ${PYTHON_EXTRA_FILE}\
+      ${FINK_HOME}/bin/${SURVEY}/extract_ssobulk.py ${LIMIT_ARGS}
+  else
+    echo -e >&2 "${SERROR} sso_ztf_lc_aggregated_${YEAR}${MONTH}.parquet does not exist."
+    echo -e >&2 "${SSTOP} Merging aborted..."
+    exit 1
+  fi
+fi
