Rewrite pixel128

diff --git a/bin/fink_db b/bin/fink_db
--- a/bin/fink_db
+++ b/bin/fink_db
@@ -228,6 +228,10 @@ if [[ ${MAIN_TABLE} == true ]]; then
     echo -e "${SINFO} Using Spark resources: ${RESOURCES}"
     echo -e "${SSTEP} Science archival"
     fink start archive_science -s ${SURVEY} -c ${conf} -night ${NIGHT} ${RESOURCES} > ${FINK_HOME}/broker_logs/archive_science_${SURVEY}_${NIGHT}.log 2>&1
+    if [[ $? != 0 ]]; then
+      echo -e "${SERROR} when archiving science. Check local logs or artifacts on the CI."
+      exit 1
+    fi
   else
     echo -e "${SERROR} No data at ${AGG_DATA_PREFIX}/science/year=${YEAR}/month=${MONTH}/day=${DAY}"
     echo -e "${SERROR} Did you run --merge before?"
@@ -300,7 +304,7 @@ if [[ ${INDEX_TABLES} == true ]]; then
       # for v8 we should change the rowkey to pixel128_firstDiaSourceMjdTai_diaObjectId
       # fink start archive_index -s ${SURVEY} -c ${conf} -night ${NIGHT} ${RESOURCES} -index_table pixel128_firstDiaSourceMjdTai_diaObjectId > ${FINK_HOME}/broker_logs/index_pixel128_firstDiaSourceMjdTai_diaObjectId_${SURVEY}_${NIGHT}.log 2>&1
       fink start archive_index -s ${SURVEY} -c ${conf} -night ${NIGHT} ${RESOURCES} -index_table pixel128_diaObjectId > ${FINK_HOME}/broker_logs/index_pixel128_diaObjectId_${SURVEY}_${NIGHT}.log 2>&1
-      fink start archive_index -s ${SURVEY} -c ${conf} -night ${NIGHT} ${RESOURCES} -index_table forcedSources_diaObjectId_midpointMjdTai > ${FINK_HOME}/broker_logs/index_forcedSources_diaObjectId_midpointMjdTai_${SURVEY}_${NIGHT}.log 2>&1
+      # fink start archive_index -s ${SURVEY} -c ${conf} -night ${NIGHT} ${RESOURCES} -index_table forcedSources_diaObjectId_midpointMjdTai > ${FINK_HOME}/broker_logs/index_forcedSources_diaObjectId_midpointMjdTai_${SURVEY}_${NIGHT}.log 2>&1
     fi
   else
     echo -e "${SERROR} No data at ${AGG_DATA_PREFIX}/science/year=${YEAR}/month=${MONTH}/day=${DAY}"
