Add options to the SSOFT controller

diff --git a/bin/fink_ssoft b/bin/fink_ssoft
--- a/bin/fink_ssoft
+++ b/bin/fink_ssoft
@@ -82,8 +82,19 @@ while [ "$#" -gt 0 ]; do
       UPDATE_DATA=true
       shift 1
       ;;
+    --list-data)
+      LIST_DATA=true
+      shift 1
     --run-ssoft)
       RUN_SSOFT=true
+      shift 1
+      ;;
+    --link-ssoft)
+      LINK_SSOFT=true
+      shift 1
+      ;;
+    --list-ssoft)
+      LIST_SSOFT=true
       shift 1
       ;;
     -*)
@@ -115,12 +126,16 @@ Options:
   -spark-cores-max      Total number of cores to use for all executors (Default is 100)
   -spark-executor-cores Number of cores per executor (Default is 2)
   --reconstruct-data    Reconstruct all aggregated data and ephemerides from 2019 until now.
-  --update-data         Add latest month data and ephemerides to the current file.
-  --run-ssoft           Run the computation of the SSOFT
+  --update-data         Add latest month data and ephemerides to the latest file.
+  --list-data           List all aggregated files available, with their version
+  --run-ssoft           Run the computation of the SSOFT. By defaut is uses the latest aggregated file.
+  --link-ssoft          Create a version agnostic SSOFT folder, with the latest version data
+  --list-ssoft          List all available SSOFT on HDFS
 
 Examples:
 fink_ssoft -s ztf --reconstruct-data                          # Reconstruct all database
 fink_ssoft -s ztf --update-data                               # Add last month data
+fink_ssoft -s ztf --list-data                                 # List all aggregated files
 fink_ssoft -s ztf --run-ssoft -model SHG1G2                   # Compute SHG1G2 SSOFT
 fink_ssoft -s ztf --run-ssoft -model SHG1G2 -version 2025.04  # Compute SHG1G2 SSOFT until 2025.04
 fink_ssoft -s ztf --run-ssoft -model SHG1G2 -limit 10         # Compute SHG1G2 SSOFT with 100 objects only
@@ -132,6 +147,7 @@ fink_ssoft -s ztf --run-ssoft -model HG
 fink_ssoft -s ztf --run-ssoft -model HG1G2
 fink_ssoft -s ztf --run-ssoft -model SHG1G2
 fink_ssoft -s ztf --run-ssoft -model SSHG1G2
+fink_ssoft -s ztf --link-ssoft
 
 Notes: If you lose all your ephemerides data, just reconstruct everything with
 fink_ssoft -s ztf --reconstruct-data
@@ -170,6 +186,21 @@ else
 fi
 
 source $conf
+
+#################################
+# Listings
+
+if [[ ${LIST_DATA} == true ]]; then
+  echo -e "${SINFO} Listing aggregated files"
+  hdfs dfs -du -h | grep sso_ztf_lc_aggregated_*
+  exit 0
+fi
+
+if [[ ${LIST_SSOFT} == true ]]; then
+  echo -e "${SINFO} Listing SSOFT (TBD)"
+  exit 0
+fi
+
 
 #################################
 # Data aggregation
@@ -236,7 +267,8 @@ if [[ ${RUN_SSOFT} == true ]]; then
     echo -e "Computing the SSOFT for the model ${MODEL}..."
     # Run the script
   else
-    echo -e >&2 "${SERROR} File sso_ztf_lc_aggregated_${YEAR}.${MONTH}.parquet exists. Move it before aggregation."
+    echo -e >&2 "${SERROR} sso_ztf_lc_aggregated_${YEAR}.${MONTH}.parquet does not exist."
+    echo -e >&2 "${SERROR} Create it, or specify another existing version."
     echo -e >&2 "${SSTOP} Merging aborted..."
     exit 1
   fi
@@ -248,7 +280,7 @@ if [[ ${LINK_SSOFT} == true ]]; then
   # Check the file we want to link exists
   $(hdfs dfs -test -d sso_ztf_lc_aggregated_${YEAR}.${MONTH}.parquet)
   if [[ $? != 0 ]]; then
-    echo -e >&2 "${SERROR} sso_ztf_lc_aggregated_${YEAR}.${MONTH}.parquet is not found on HDFS."
+    echo -e >&2 "${SERROR} sso_ztf_lc_aggregated_${YEAR}.${MONTH}.parquet does not exist."
     echo -e >&2 "${SERROR} Aborting..."
     exit 1
   fi
